# .github/workflows/analyze.yml
name: Analyze Usage

on:
  workflow_call:
    inputs:
      instance_id:
        required: true
        type: string
      region:
        required: true
        type: string
      requested_type:
        required: false
        type: string

jobs:
  analyze:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: ${{ inputs.region }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install boto3

      - name: Debug AWS Env Vars
        run: env | grep AWS

      - name: Analyze Usage
        run: python scripts/analyze_usage.py ${{ inputs.instance_id }} ${{ inputs.region }}

      - name: Recommend Instance Type
        run: python scripts/instance_recommender.py

      - name: Upload Recommendation
        uses: actions/upload-artifact@v4
        with:
          name: suggestion
          path: suggestion.json
