name: Analyze Usage

on:
  workflow_dispatch:
    inputs:
      instance_id:
        required: true
      region:
        required: true
      requested_type:
        required: false

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install boto3

      - name: Analyze Usage
        run: |
          python scripts/analyze_usage.py ${{ github.event.inputs.instance_id }} ${{ github.event.inputs.region }}

      - name: Recommend Instance Type
        run: |
          python scripts/instance_recommender.py

      - name: Upload Recommendation
        uses: actions/upload-artifact@v3
        with:
          name: suggestion
          path: suggestion.json