name: Approval for Change

on:
  workflow_run:
    workflows: ["Plan Instance Type Change"]
    types:
      - completed

jobs:
  approve:
    if: ${{ needs.plan.outputs.approval_required == 'true' }}
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://github.com/${{ github.repository }}/actions
    steps:
      - name: Wait for Manual Approval
        run: echo "Waiting for manual approval..."
