name: Trigger EC2 Optimization

on:
  workflow_dispatch:
    inputs:
      instance_id:
        description: 'EC2 Instance ID'
        required: true
      region:
        description: 'AWS Region'
        required: true
      requested_type:
        description: 'Requested EC2 instance type (optional)'
        required: false

jobs:
  start:
    uses: ./.github/workflows/analyze.yml  # Call analyze.yml as reusable workflow
    with:
      instance_id: ${{ github.event.inputs.instance_id }}
      region: ${{ github.event.inputs.region }}
      requested_type: ${{ github.event.inputs.requested_type }}
